name: Grading workflow
on:
  push:
    paths:
      - ".github/dependabot.yml"
  workflow_dispatch:

jobs:
  grade-learner:
    if: github.event_name == 'push' # Apply additional filters as needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grade exercise-configure-dependabot activity
        id: events
        uses: ./.github/actions/local-action

      - name: Grading results
        uses: githubtraining/looking-glass-action@v1.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          feedback: ${{ steps.events.outputs.reports }}
  troubleshoot-activity:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: troubleshooting steps
        run: echo "See the following doc for help with configuring dependabot:https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates" #Help the user to troubleshoot the activity
