name: Initial repo configuration
#on: push

jobs:
  setup-repo:
    runs-on: ubuntu-latest
    if: github.event.commits[0].message == 'Initial commit' && github.repository != 'githubtraining/exercise-configure-dependabot'
    steps:
    #   - name: Checkout repo
    #     uses: actions/checkout@v2

    #   - name: Configure exercise
    #     uses: githubtraining/stage-commits-action@main
